definitions:
  common.Result:
    properties:
      code:
        type: integer
      data: {}
      errs: {}
      msg:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: im在线通信系统前后台接口文档
  title: Im在线通信系统接口文档
  version: 1.0 版本
paths:
  /front/user/login:
    get:
      consumes:
      - application/json
      description: user login
      parameters:
      - description: Id
        in: query
        name: Id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Result'
        "400":
          description: err_code：10002 参数错误； err_code：10003 校验错误
          schema:
            type: string
      summary: 用户登录接口
      tags:
      - 前端用户接口
  /front/user/register:
    post:
      consumes:
      - application/json
      description: user register
      parameters:
      - description: Id
        in: query
        name: Id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.Result'
      summary: 用户注册接口
      tags:
      - 前端用户接口
swagger: "2.0"
